export default {
   "CountryData":
   [
   {country_name:"Andorra",country_code:"AD"},
   {country_name:"United Arab Emirates",country_code:"AE"},
   {country_name:"Afghanistan",country_code:"AF"},
   {country_name:"Antigua and Barbuda",country_code:"AG"},
   {country_name:"Anguilla",country_code:"AI"},
   {country_name:"Albania",country_code:"AL"},
   {country_name:"Armenia",country_code:"AM"},
   {country_name:"Angola",country_code:"AO"},
   {country_name:"Antarctica",country_code:"AQ"},
   {country_name:"Argentina",country_code:"AR"},
   {country_name:"American Samoa",country_code:"AS"},
   {country_name:"Austria",country_code:"AT"},
   {country_name:"Australia",country_code:"AU"},
   {country_name:"Aruba",country_code:"AW"},
   {country_name:"Åland",country_code:"AX"},
   {country_name:"Azerbaijan",country_code:"AZ"},
   {country_name:"Bosnia and Herzegovina",country_code:"BA"},
   {country_name:"Barbados",country_code:"BB"},
   {country_name:"Bangladesh",country_code:"BD"},
   {country_name:"Belgium",country_code:"BE"},
   {country_name:"Burkina Faso",country_code:"BF"},
   {country_name:"Bulgaria",country_code:"BG"},
   {country_name:"Bahrain",country_code:"BH"},
   {country_name:"Burundi",country_code:"BI"},
   {country_name:"Benin",country_code:"BJ"},
   {country_name:"Saint Barthélemy",country_code:"BL"},
   {country_name:"Bermuda",country_code:"BM"},
   {country_name:"Brunei",country_code:"BN"},
   {country_name:"Bolivia",country_code:"BO"},
   {country_name:"Bonaire",country_code:"BQ"},
   {country_name:"Brazil",country_code:"BR"},
   {country_name:"Bahamas",country_code:"BS"},
   {country_name:"Bhutan",country_code:"BT"},
   {country_name:"Bouvet Island",country_code:"BV"},
   {country_name:"Botswana",country_code:"BW"},
   {country_name:"Belarus",country_code:"BY"},
   {country_name:"Belize",country_code:"BZ"},
   {country_name:"Canada",country_code:"CA"},
   {country_name:"Cocos [Keeling] Islands",country_code:"CC"},
   {country_name:"Democratic Republic of the Congo",country_code:"CD"},
   {country_name:"Central African Republic",country_code:"CF"},
   {country_name:"Republic of the Congo",country_code:"CG"},
   {country_name:"Switzerland",country_code:"CH"},
   {country_name:"Ivory Coast",country_code:"CI"},
   {country_name:"Cook Islands",country_code:"CK"},
   {country_name:"Chile",country_code:"CL"},
   {country_name:"Cameroon",country_code:"CM"},
   {country_name:"China",country_code:"CN"},
   {country_name:"Colombia",country_code:"CO"},
   {country_name:"Costa Rica",country_code:"CR"},
   {country_name:"Cuba",country_code:"CU"},
   {country_name:"Cape Verde",country_code:"CV"},
   {country_name:"Curacao",country_code:"CW"},
   {country_name:"Christmas Island",country_code:"CX"},
   {country_name:"Cyprus",country_code:"CY"},
   {country_name:"Czech Republic",country_code:"CZ"},
   {country_name:"Germany",country_code:"DE"},
   {country_name:"Djibouti",country_code:"DJ"},
   {country_name:"Denmark",country_code:"DK"},
   {country_name:"Dominica",country_code:"DM"},
   {country_name:"Dominican Republic",country_code:"DO"},
   {country_name:"Algeria",country_code:"DZ"},
   {country_name:"Ecuador",country_code:"EC"},
   {country_name:"Estonia",country_code:"EE"},
   {country_name:"Egypt",country_code:"EG"},
   {country_name:"Western Sahara",country_code:"EH"},
   {country_name:"Eritrea",country_code:"ER"},
   {country_name:"Spain",country_code:"ES"},
   {country_name:"Ethiopia",country_code:"ET"},
   {country_name:"Finland",country_code:"FI"},
   {country_name:"Fiji",country_code:"FJ"},
   {country_name:"Falkland Islands",country_code:"FK"},
   {country_name:"Micronesia",country_code:"FM"},
   {country_name:"Faroe Islands",country_code:"FO"},
   {country_name:"France",country_code:"FR"},
   {country_name:"Gabon",country_code:"GA"},
   {country_name:"United Kingdom",country_code:"GB"},
   {country_name:"Grenada",country_code:"GD"},
   {country_name:"Georgia",country_code:"GE"},
   {country_name:"French Guiana",country_code:"GF"},
   {country_name:"Guernsey",country_code:"GG"},
   {country_name:"Ghana",country_code:"GH"},
   {country_name:"Gibraltar",country_code:"GI"},
   {country_name:"Greenland",country_code:"GL"},
   {country_name:"Gambia",country_code:"GM"},
   {country_name:"Guinea",country_code:"GN"},
   {country_name:"Guadeloupe",country_code:"GP"},
   {country_name:"Equatorial Guinea",country_code:"GQ"},
   {country_name:"Greece",country_code:"GR"},
   {country_name:"South Georgia and the South Sandwich Islands",country_code:"GS"},
   {country_name:"Guatemala",country_code:"GT"},
   {country_name:"Guam",country_code:"GU"},
   {country_name:"Guinea-Bissau",country_code:"GW"},
   {country_name:"Guyana",country_code:"GY"},
   {country_name:"Hong Kong",country_code:"HK"},
   {country_name:"Heard Island and McDonald Islands",country_code:"HM"},
   {country_name:"Honduras",country_code:"HN"},
   {country_name:"Croatia",country_code:"HR"},
   {country_name:"Haiti",country_code:"HT"},
   {country_name:"Hungary",country_code:"HU"},
   {country_name:"Indonesia",country_code:"ID"},
   {country_name:"Ireland",country_code:"IE"},
   {country_name:"Israel",country_code:"IL"},
   {country_name:"Isle of Man",country_code:"IM"},
   {country_name:"India",country_code:"IN"},
   {country_name:"British Indian Ocean Territory",country_code:"IO"},
   {country_name:"Iraq",country_code:"IQ"},
   {country_name:"Iran",country_code:"IR"},
   {country_name:"Iceland",country_code:"IS"},
   {country_name:"Italy",country_code:"IT"},
   {country_name:"Jersey",country_code:"JE"},
   {country_name:"Jamaica",country_code:"JM"},
   {country_name:"Jordan",country_code:"JO"},
   {country_name:"Japan",country_code:"JP"},
   {country_name:"Kenya",country_code:"KE"},
   {country_name:"Kyrgyzstan",country_code:"KG"},
   {country_name:"Cambodia",country_code:"KH"},
   {country_name:"Kiribati",country_code:"KI"},
   {country_name:"Comoros",country_code:"KM"},
   {country_name:"Saint Kitts and Nevis",country_code:"KN"},
   {country_name:"North Korea",country_code:"KP"},
   {country_name:"South Korea",country_code:"KR"},
   {country_name:"Kuwait",country_code:"KW"},
   {country_name:"Cayman Islands",country_code:"KY"},
   {country_name:"Kazakhstan",country_code:"KZ"},
   {country_name:"Laos",country_code:"LA"},
   {country_name:"Lebanon",country_code:"LB"},
   {country_name:"Saint Lucia",country_code:"LC"},
   {country_name:"Liechtenstein",country_code:"LI"},
   {country_name:"Sri Lanka",country_code:"LK"},
   {country_name:"Liberia",country_code:"LR"},
   {country_name:"Lesotho",country_code:"LS"},
   {country_name:"Lithuania",country_code:"LT"},
   {country_name:"Luxembourg",country_code:"LU"},
   {country_name:"Latvia",country_code:"LV"},
   {country_name:"Libya",country_code:"LY"},
   {country_name:"Morocco",country_code:"MA"},
   {country_name:"Monaco",country_code:"MC"},
   {country_name:"Moldova",country_code:"MD"},
   {country_name:"Montenegro",country_code:"ME"},
   {country_name:"Saint Martin",country_code:"MF"},
   {country_name:"Madagascar",country_code:"MG"},
   {country_name:"Marshall Islands",country_code:"MH"},
   {country_name:"North Macedonia",country_code:"MK"},
   {country_name:"Mali",country_code:"ML"},
   {country_name:"Myanmar [Burma]",country_code:"MM"},
   {country_name:"Mongolia",country_code:"MN"},
   {country_name:"Macao",country_code:"MO"},
   {country_name:"Northern Mariana Islands",country_code:"MP"},
   {country_name:"Martinique",country_code:"MQ"},
   {country_name:"Mauritania",country_code:"MR"},
   {country_name:"Montserrat",country_code:"MS"},
   {country_name:"Malta",country_code:"MT"},
   {country_name:"Mauritius",country_code:"MU"},
   {country_name:"Maldives",country_code:"MV"},
   {country_name:"Malawi",country_code:"MW"},
   {country_name:"Mexico",country_code:"MX"},
   {country_name:"Malaysia",country_code:"MY"},
   {country_name:"Mozambique",country_code:"MZ"},
   {country_name:"Namibia",country_code:"NA"},
   {country_name:"New Caledonia",country_code:"NC"},
   {country_name:"Niger",country_code:"NE"},
   {country_name:"Norfolk Island",country_code:"NF"},
   {country_name:"Nigeria",country_code:"NG"},
   {country_name:"Nicaragua",country_code:"NI"},
   {country_name:"Netherlands",country_code:"NL"},
   {country_name:"Norway",country_code:"NO"},
   {country_name:"Nepal",country_code:"NP"},
   {country_name:"Nauru",country_code:"NR"},
   {country_name:"Niue",country_code:"NU"},
   {country_name:"New Zealand",country_code:"NZ"},
   {country_name:"Oman",country_code:"OM"},
   {country_name:"Panama",country_code:"PA"},
   {country_name:"Peru",country_code:"PE"},
   {country_name:"French Polynesia",country_code:"PF"},
   {country_name:"Papua New Guinea",country_code:"PG"},
   {country_name:"Philippines",country_code:"PH"},
   {country_name:"Pakistan",country_code:"PK"},
   {country_name:"Poland",country_code:"PL"},
   {country_name:"Saint Pierre and Miquelon",country_code:"PM"},
   {country_name:"Pitcairn Islands",country_code:"PN"},
   {country_name:"Puerto Rico",country_code:"PR"},
   {country_name:"Palestine",country_code:"PS"},
   {country_name:"Portugal",country_code:"PT"},
   {country_name:"Palau",country_code:"PW"},
   {country_name:"Paraguay",country_code:"PY"},
   {country_name:"Qatar",country_code:"QA"},
   {country_name:"Réunion",country_code:"RE"},
   {country_name:"Romania",country_code:"RO"},
   {country_name:"Serbia",country_code:"RS"},
   {country_name:"Russia",country_code:"RU"},
   {country_name:"Rwanda",country_code:"RW"},
   {country_name:"Saudi Arabia",country_code:"SA"},
   {country_name:"Solomon Islands",country_code:"SB"},
   {country_name:"Seychelles",country_code:"SC"},
   {country_name:"Sudan",country_code:"SD"},
   {country_name:"Sweden",country_code:"SE"},
   {country_name:"Singapore",country_code:"SG"},
   {country_name:"Saint Helena",country_code:"SH"},
   {country_name:"Slovenia",country_code:"SI"},
   {country_name:"Svalbard and Jan Mayen",country_code:"SJ"},
   {country_name:"Slovakia",country_code:"SK"},
   {country_name:"Sierra Leone",country_code:"SL"},
   {country_name:"San Marino",country_code:"SM"},
   {country_name:"Senegal",country_code:"SN"},
   {country_name:"Somalia",country_code:"SO"},
   {country_name:"Suriname",country_code:"SR"},
   {country_name:"South Sudan",country_code:"SS"},
   {country_name:"São Tomé and Príncipe",country_code:"ST"},
   {country_name:"El Salvador",country_code:"SV"},
   {country_name:"Sint Maarten",country_code:"SX"},
   {country_name:"Syria",country_code:"SY"},
   {country_name:"Swaziland",country_code:"SZ"},
   {country_name:"Turks and Caicos Islands",country_code:"TC"},
   {country_name:"Chad",country_code:"TD"},
   {country_name:"French Southern Territories",country_code:"TF"},
   {country_name:"Togo",country_code:"TG"},
   {country_name:"Thailand",country_code:"TH"},
   {country_name:"Tajikistan",country_code:"TJ"},
   {country_name:"Tokelau",country_code:"TK"},
   {country_name:"East Timor",country_code:"TL"},
   {country_name:"Turkmenistan",country_code:"TM"},
   {country_name:"Tunisia",country_code:"TN"},
   {country_name:"Tonga",country_code:"TO"},
   {country_name:"Turkey",country_code:"TR"},
   {country_name:"Trinidad and Tobago",country_code:"TT"},
   {country_name:"Tuvalu",country_code:"TV"},
   {country_name:"Taiwan",country_code:"TW"},
   {country_name:"Tanzania",country_code:"TZ"},
   {country_name:"Ukraine",country_code:"UA"},
   {country_name:"Uganda",country_code:"UG"},
   {country_name:"U.S. Minor Outlying Islands",country_code:"UM"},
   {country_name:"United States",country_code:"US"},
   {country_name:"Uruguay",country_code:"UY"},
   {country_name:"Uzbekistan",country_code:"UZ"},
   {country_name:"Vatican City",country_code:"VA"},
   {country_name:"Saint Vincent and the Grenadines",country_code:"VC"},
   {country_name:"Venezuela",country_code:"VE"},
   {country_name:"British Virgin Islands",country_code:"VG"},
   {country_name:"U.S. Virgin Islands",country_code:"VI"},
   {country_name:"Vietnam",country_code:"VN"},
   {country_name:"Vanuatu",country_code:"VU"},
   {country_name:"Wallis and Futuna",country_code:"WF"},
   {country_name:"Samoa",country_code:"WS"},
   {country_name:"Kosovo",country_code:"XK"},
   {country_name:"Yemen",country_code:"YE"},
   {country_name:"Mayotte",country_code:"YT"},
   {country_name:"South Africa",country_code:"ZA"},
   {country_name:"Zambia",country_code:"ZM"},
   {country_name:"Zimbabwe",country_code:"ZW"}
],
   "CurrencyData":
   [{currency_code:"AED",currency_name:"UAE Dirham"},
   {currency_code:"AFN",currency_name:"Afghani"},
   {currency_code:"ALL",currency_name:"Lek"},
   {currency_code:"AMD",currency_name:"Armenian Dram"},
   {currency_code:"ANG",currency_name:"Netherlands Antillean Guilder"},
   {currency_code:"AOA",currency_name:"Kwanza"},
   {currency_code:"ARS",currency_name:"Argentine Peso"},
   {currency_code:"AUD",currency_name:"Australian Dollar"},
   {currency_code:"AWG",currency_name:"Aruban Florin"},
   {currency_code:"AZN",currency_name:"Azerbaijan Manat"},
   {currency_code:"BAM",currency_name:"Convertible Mark"},
   {currency_code:"BBD",currency_name:"Barbados Dollar"},
   {currency_code:"BDT",currency_name:"Taka"},
   {currency_code:"BGN",currency_name:"Bulgarian Lev"},
   {currency_code:"BHD",currency_name:"Bahraini Dinar"},
   {currency_code:"BIF",currency_name:"Burundi Franc"},
   {currency_code:"BMD",currency_name:"Bermudian Dollar"},
   {currency_code:"BND",currency_name:"Brunei Dollar"},
   {currency_code:"BOB",currency_name:"Boliviano"},
   {currency_code:"BOV",currency_name:"Mvdol"},
   {currency_code:"BRL",currency_name:"Brazilian Real"},
   {currency_code:"BSD",currency_name:"Bahamian Dollar"},
   {currency_code:"BTN",currency_name:"Ngultrum"},
   {currency_code:"BWP",currency_name:"Pula"},
   {currency_code:"BYN",currency_name:"Belarusian Ruble"},
   {currency_code:"BZD",currency_name:"Belize Dollar"},
   {currency_code:"CAD",currency_name:"Canadian Dollar"},
   {currency_code:"CDF",currency_name:"Congolese Franc"},
   {currency_code:"CHE",currency_name:"WIR Euro"},
   {currency_code:"CHF",currency_name:"Swiss Franc"},
   {currency_code:"CHW",currency_name:"WIR Franc"},
   {currency_code:"CLF",currency_name:"Unidad de Fomento"},
   {currency_code:"CLP",currency_name:"Chilean Peso"},
   {currency_code:"CNY",currency_name:"Yuan Renminbi"},
   {currency_code:"COP",currency_name:"Colombian Peso"},
   {currency_code:"COU",currency_name:"Unidad de Valor Real"},
   {currency_code:"CRC",currency_name:"Costa Rican Colon"},
   {currency_code:"CUC",currency_name:"Peso Convertible"},
   {currency_code:"CUP",currency_name:"Cuban Peso"},
   {currency_code:"CVE",currency_name:"Cabo Verde Escudo"},
   {currency_code:"CZK",currency_name:"Czech Koruna"},
   {currency_code:"DJF",currency_name:"Djibouti Franc"},
   {currency_code:"DKK",currency_name:"Danish Krone"},
   {currency_code:"DOP",currency_name:"Dominican Peso"},
   {currency_code:"DZD",currency_name:"Algerian Dinar"},
   {currency_code:"EGP",currency_name:"Egyptian Pound"},
   {currency_code:"ERN",currency_name:"Nakfa"},
   {currency_code:"ETB",currency_name:"Ethiopian Birr"},
   {currency_code:"EUR",currency_name:"Euro"},
   {currency_code:"FJD",currency_name:"Fiji Dollar"},
   {currency_code:"FKP",currency_name:"Falkland Islands Pound"},
   {currency_code:"GBP",currency_name:"Pound Sterling"},
   {currency_code:"GEL",currency_name:"Lari"},
   {currency_code:"GHS",currency_name:"Ghana Cedi"},
   {currency_code:"GIP",currency_name:"Gibraltar Pound"},
   {currency_code:"GMD",currency_name:"Dalasi"},
   {currency_code:"GNF",currency_name:"Guinean Franc"},
   {currency_code:"GTQ",currency_name:"Quetzal"},
   {currency_code:"GYD",currency_name:"Guyana Dollar"},
   {currency_code:"HKD",currency_name:"Hong Kong Dollar"},
   {currency_code:"HNL",currency_name:"Lempira"},
   {currency_code:"HRK",currency_name:"Kuna"},
   {currency_code:"HTG",currency_name:"Gourde"},
   {currency_code:"HUF",currency_name:"Forint"},
   {currency_code:"IDR",currency_name:"Rupiah"},
   {currency_code:"ILS",currency_name:"New Israeli Sheqel"},
   {currency_code:"INR",currency_name:"Indian Rupee"},
   {currency_code:"IQD",currency_name:"Iraqi Dinar"},
   {currency_code:"IRR",currency_name:"Iranian Rial"},
   {currency_code:"ISK",currency_name:"Iceland Krona"},
   {currency_code:"JMD",currency_name:"Jamaican Dollar"},
   {currency_code:"JOD",currency_name:"Jordanian Dinar"},
   {currency_code:"JPY",currency_name:"Yen"},
   {currency_code:"KES",currency_name:"Kenyan Shilling"},
   {currency_code:"KGS",currency_name:"Som"},
   {currency_code:"KHR",currency_name:"Riel"},
   {currency_code:"KMF",currency_name:"Comorian Franc "},
   {currency_code:"KPW",currency_name:"North Korean Won"},
   {currency_code:"KRW",currency_name:"Won"},
   {currency_code:"KWD",currency_name:"Kuwaiti Dinar"},
   {currency_code:"KYD",currency_name:"Cayman Islands Dollar"},
   {currency_code:"KZT",currency_name:"Tenge"},
   {currency_code:"LAK",currency_name:"Lao Kip"},
   {currency_code:"LBP",currency_name:"Lebanese Pound"},
   {currency_code:"LKR",currency_name:"Sri Lanka Rupee"},
   {currency_code:"LRD",currency_name:"Liberian Dollar"},
   {currency_code:"LSL",currency_name:"Loti"},
   {currency_code:"LYD",currency_name:"Libyan Dinar"},
   {currency_code:"MAD",currency_name:"Moroccan Dirham"},
   {currency_code:"MDL",currency_name:"Moldovan Leu"},
   {currency_code:"MGA",currency_name:"Malagasy Ariary"},
   {currency_code:"MKD",currency_name:"Denar"},
   {currency_code:"MMK",currency_name:"Kyat"},
   {currency_code:"MNT",currency_name:"Tugrik"},
   {currency_code:"MOP",currency_name:"Pataca"},
   {currency_code:"MRU",currency_name:"Ouguiya"},
   {currency_code:"MUR",currency_name:"Mauritius Rupee"},
   {currency_code:"MVR",currency_name:"Rufiyaa"},
   {currency_code:"MWK",currency_name:"Malawi Kwacha"},
   {currency_code:"MXN",currency_name:"Mexican Peso"},
   {currency_code:"MXV",currency_name:"Mexican Unidad de Inversion (UDI)"},
   {currency_code:"MYR",currency_name:"Malaysian Ringgit"},
   {currency_code:"MZN",currency_name:"Mozambique Metical"},
   {currency_code:"NAD",currency_name:"Namibia Dollar"},
   {currency_code:"NGN",currency_name:"Naira"},
   {currency_code:"NIO",currency_name:"Cordoba Oro"},
   {currency_code:"NOK",currency_name:"Norwegian Krone"},
   {currency_code:"NPR",currency_name:"Nepalese Rupee"},
   {currency_code:"NZD",currency_name:"New Zealand Dollar"},
   {currency_code:"OMR",currency_name:"Rial Omani"},
   {currency_code:"PAB",currency_name:"Balboa"},
   {currency_code:"PEN",currency_name:"Sol"},
   {currency_code:"PGK",currency_name:"Kina"},
   {currency_code:"PHP",currency_name:"Philippine Peso"},
   {currency_code:"PKR",currency_name:"Pakistan Rupee"},
   {currency_code:"PLN",currency_name:"Zloty"},
   {currency_code:"PYG",currency_name:"Guarani"},
   {currency_code:"QAR",currency_name:"Qatari Rial"},
   {currency_code:"RON",currency_name:"Romanian Leu"},
   {currency_code:"RSD",currency_name:"Serbian Dinar"},
   {currency_code:"RUB",currency_name:"Russian Ruble"},
   {currency_code:"RWF",currency_name:"Rwanda Franc"},
   {currency_code:"SAR",currency_name:"Saudi Riyal"},
   {currency_code:"SBD",currency_name:"Solomon Islands Dollar"},
   {currency_code:"SCR",currency_name:"Seychelles Rupee"},
   {currency_code:"SDG",currency_name:"Sudanese Pound"},
   {currency_code:"SEK",currency_name:"Swedish Krona"},
   {currency_code:"SGD",currency_name:"Singapore Dollar"},
   {currency_code:"SHP",currency_name:"Saint Helena Pound"},
   {currency_code:"SLL",currency_name:"Leone"},
   {currency_code:"SOS",currency_name:"Somali Shilling"},
   {currency_code:"SRD",currency_name:"Surinam Dollar"},
   {currency_code:"SSP",currency_name:"South Sudanese Pound"},
   {currency_code:"STN",currency_name:"Dobra"},
   {currency_code:"SVC",currency_name:"El Salvador Colon"},
   {currency_code:"SYP",currency_name:"Syrian Pound"},
   {currency_code:"SZL",currency_name:"Lilangeni"},
   {currency_code:"THB",currency_name:"Baht"},
   {currency_code:"TJS",currency_name:"Somoni"},
   {currency_code:"TMT",currency_name:"Turkmenistan New Manat"},
   {currency_code:"TND",currency_name:"Tunisian Dinar"},
   {currency_code:"TOP",currency_name:"Pa’anga"},
   {currency_code:"TRY",currency_name:"Turkish Lira"},
   {currency_code:"TTD",currency_name:"Trinidad and Tobago Dollar"},
   {currency_code:"TWD",currency_name:"New Taiwan Dollar"},
   {currency_code:"TZS",currency_name:"Tanzanian Shilling"},
   {currency_code:"UAH",currency_name:"Hryvnia"},
   {currency_code:"UGX",currency_name:"Uganda Shilling"},
   {currency_code:"USD",currency_name:"US Dollar"},
   {currency_code:"USN",currency_name:"US Dollar (Next day)"},
   {currency_code:"UYI",currency_name:"Uruguay Peso en Unidades Indexadas (UI)"},
   {currency_code:"UYU",currency_name:"Peso Uruguayo"},
   {currency_code:"UYW",currency_name:"Unidad Previsional"},
   {currency_code:"UZS",currency_name:"Uzbekistan Sum"},
   {currency_code:"VES",currency_name:"Bolívar Soberano"},
   {currency_code:"VND",currency_name:"Dong"},
   {currency_code:"VUV",currency_name:"Vatu"},
   {currency_code:"WST",currency_name:"Tala"},
   {currency_code:"XAF",currency_name:"CFA Franc BEAC"},
   {currency_code:"XAG",currency_name:"Silver"},
   {currency_code:"XAU",currency_name:"Gold"},
   {currency_code:"XBA",currency_name:"Bond Markets Unit European Composite Unit (EURCO)"},
   {currency_code:"XBB",currency_name:"Bond Markets Unit European Monetary Unit (E.M.U.-6)"},
   {currency_code:"XBC",currency_name:"Bond Markets Unit European Unit of Account 9 (E.U.A.-9)"},
   {currency_code:"XBD",currency_name:"Bond Markets Unit European Unit of Account 17 (E.U.A.-17)"},
   {currency_code:"XCD",currency_name:"East Caribbean Dollar"},
   {currency_code:"XDR",currency_name:"SDR (Special Drawing Right)"},
   {currency_code:"XOF",currency_name:"CFA Franc BCEAO"},
   {currency_code:"XPD",currency_name:"Palladium"},
   {currency_code:"XPF",currency_name:"CFP Franc"},
   {currency_code:"XPT",currency_name:"Platinum"},
   {currency_code:"XSU",currency_name:"Sucre"},
   {currency_code:"XTS",currency_name:"Codes specifically reserved for testing purposes"},
   {currency_code:"XUA",currency_name:"ADB Unit of Account"},
   {currency_code:"XXX",currency_name:"The codes assigned for transactions where no currency is involved"},
   {currency_code:"YER",currency_name:"Yemeni Rial"},
   {currency_code:"ZAR",currency_name:"Rand"},
   {currency_code:"ZMW",currency_name:"Zambian Kwacha"},
   {currency_code:"ZWL",currency_name:"Zimbabwe Dollar"},
   {currency_code:"AED",currency_name:"UAE Dirham"},
   {currency_code:"AFN",currency_name:"Afghani"},
   {currency_code:"ALL",currency_name:"Lek"},
   {currency_code:"AMD",currency_name:"Armenian Dram"},
   {currency_code:"ANG",currency_name:"Netherlands Antillean Guilder"},
   {currency_code:"AOA",currency_name:"Kwanza"},
   {currency_code:"ARS",currency_name:"Argentine Peso"},
   {currency_code:"AUD",currency_name:"Australian Dollar"},
   {currency_code:"AWG",currency_name:"Aruban Florin"},
   {currency_code:"AZN",currency_name:"Azerbaijan Manat"},
   {currency_code:"BAM",currency_name:"Convertible Mark"},
   {currency_code:"BBD",currency_name:"Barbados Dollar"},
   {currency_code:"BDT",currency_name:"Taka"},
   {currency_code:"BGN",currency_name:"Bulgarian Lev"},
   {currency_code:"BHD",currency_name:"Bahraini Dinar"},
   {currency_code:"BIF",currency_name:"Burundi Franc"},
   {currency_code:"BMD",currency_name:"Bermudian Dollar"},
   {currency_code:"BND",currency_name:"Brunei Dollar"},
   {currency_code:"BOB",currency_name:"Boliviano"},
   {currency_code:"BOV",currency_name:"Mvdol"},
   {currency_code:"BRL",currency_name:"Brazilian Real"},
   {currency_code:"BSD",currency_name:"Bahamian Dollar"},
   {currency_code:"BTN",currency_name:"Ngultrum"},
   {currency_code:"BWP",currency_name:"Pula"},
   {currency_code:"BYN",currency_name:"Belarusian Ruble"},
   {currency_code:"BZD",currency_name:"Belize Dollar"},
   {currency_code:"CAD",currency_name:"Canadian Dollar"},
   {currency_code:"CDF",currency_name:"Congolese Franc"},
   {currency_code:"CHE",currency_name:"WIR Euro"},
   {currency_code:"CHF",currency_name:"Swiss Franc"},
   {currency_code:"CHW",currency_name:"WIR Franc"},
   {currency_code:"CLF",currency_name:"Unidad de Fomento"},
   {currency_code:"CLP",currency_name:"Chilean Peso"},
   {currency_code:"CNY",currency_name:"Yuan Renminbi"},
   {currency_code:"COP",currency_name:"Colombian Peso"},
   {currency_code:"COU",currency_name:"Unidad de Valor Real"},
   {currency_code:"CRC",currency_name:"Costa Rican Colon"},
   {currency_code:"CUC",currency_name:"Peso Convertible"},
   {currency_code:"CUP",currency_name:"Cuban Peso"},
   {currency_code:"CVE",currency_name:"Cabo Verde Escudo"},
   {currency_code:"CZK",currency_name:"Czech Koruna"},
   {currency_code:"DJF",currency_name:"Djibouti Franc"},
   {currency_code:"DKK",currency_name:"Danish Krone"},
   {currency_code:"DOP",currency_name:"Dominican Peso"},
   {currency_code:"DZD",currency_name:"Algerian Dinar"},
   {currency_code:"EGP",currency_name:"Egyptian Pound"},
   {currency_code:"ERN",currency_name:"Nakfa"},
   {currency_code:"ETB",currency_name:"Ethiopian Birr"},
   {currency_code:"EUR",currency_name:"Euro"},
   {currency_code:"FJD",currency_name:"Fiji Dollar"},
   {currency_code:"FKP",currency_name:"Falkland Islands Pound"},
   {currency_code:"GBP",currency_name:"Pound Sterling"},
   {currency_code:"GEL",currency_name:"Lari"},
   {currency_code:"GHS",currency_name:"Ghana Cedi"},
   {currency_code:"GIP",currency_name:"Gibraltar Pound"},
   {currency_code:"GMD",currency_name:"Dalasi"},
   {currency_code:"GNF",currency_name:"Guinean Franc"},
   {currency_code:"GTQ",currency_name:"Quetzal"},
   {currency_code:"GYD",currency_name:"Guyana Dollar"},
   {currency_code:"HKD",currency_name:"Hong Kong Dollar"},
   {currency_code:"HNL",currency_name:"Lempira"},
   {currency_code:"HRK",currency_name:"Kuna"},
   {currency_code:"HTG",currency_name:"Gourde"},
   {currency_code:"HUF",currency_name:"Forint"},
   {currency_code:"IDR",currency_name:"Rupiah"},
   {currency_code:"ILS",currency_name:"New Israeli Sheqel"},
   {currency_code:"INR",currency_name:"Indian Rupee"},
   {currency_code:"IQD",currency_name:"Iraqi Dinar"},
   {currency_code:"IRR",currency_name:"Iranian Rial"},
   {currency_code:"ISK",currency_name:"Iceland Krona"},
   {currency_code:"JMD",currency_name:"Jamaican Dollar"},
   {currency_code:"JOD",currency_name:"Jordanian Dinar"},
   {currency_code:"JPY",currency_name:"Yen"},
   {currency_code:"KES",currency_name:"Kenyan Shilling"},
   {currency_code:"KGS",currency_name:"Som"},
   {currency_code:"KHR",currency_name:"Riel"},
   {currency_code:"KMF",currency_name:"Comorian Franc "},
   {currency_code:"KPW",currency_name:"North Korean Won"},
   {currency_code:"KRW",currency_name:"Won"},
   {currency_code:"KWD",currency_name:"Kuwaiti Dinar"},
   {currency_code:"KYD",currency_name:"Cayman Islands Dollar"},
   {currency_code:"KZT",currency_name:"Tenge"},
   {currency_code:"LAK",currency_name:"Lao Kip"},
   {currency_code:"LBP",currency_name:"Lebanese Pound"},
   {currency_code:"LKR",currency_name:"Sri Lanka Rupee"},
   {currency_code:"LRD",currency_name:"Liberian Dollar"},
   {currency_code:"LSL",currency_name:"Loti"},
   {currency_code:"LYD",currency_name:"Libyan Dinar"},
   {currency_code:"MAD",currency_name:"Moroccan Dirham"},
   {currency_code:"MDL",currency_name:"Moldovan Leu"},
   {currency_code:"MGA",currency_name:"Malagasy Ariary"},
   {currency_code:"MKD",currency_name:"Denar"},
   {currency_code:"MMK",currency_name:"Kyat"},
   {currency_code:"MNT",currency_name:"Tugrik"},
   {currency_code:"MOP",currency_name:"Pataca"},
   {currency_code:"MRU",currency_name:"Ouguiya"},
   {currency_code:"MUR",currency_name:"Mauritius Rupee"},
   {currency_code:"MVR",currency_name:"Rufiyaa"},
   {currency_code:"MWK",currency_name:"Malawi Kwacha"},
   {currency_code:"MXN",currency_name:"Mexican Peso"},
   {currency_code:"MXV",currency_name:"Mexican Unidad de Inversion (UDI)"},
   {currency_code:"MYR",currency_name:"Malaysian Ringgit"},
   {currency_code:"MZN",currency_name:"Mozambique Metical"},
   {currency_code:"NAD",currency_name:"Namibia Dollar"},
   {currency_code:"NGN",currency_name:"Naira"},
   {currency_code:"NIO",currency_name:"Cordoba Oro"},
   {currency_code:"NOK",currency_name:"Norwegian Krone"},
   {currency_code:"NPR",currency_name:"Nepalese Rupee"},
   {currency_code:"NZD",currency_name:"New Zealand Dollar"},
   {currency_code:"OMR",currency_name:"Rial Omani"},
   {currency_code:"PAB",currency_name:"Balboa"},
   {currency_code:"PEN",currency_name:"Sol"},
   {currency_code:"PGK",currency_name:"Kina"},
   {currency_code:"PHP",currency_name:"Philippine Peso"},
   {currency_code:"PKR",currency_name:"Pakistan Rupee"},
   {currency_code:"PLN",currency_name:"Zloty"},
   {currency_code:"PYG",currency_name:"Guarani"},
   {currency_code:"QAR",currency_name:"Qatari Rial"},
   {currency_code:"RON",currency_name:"Romanian Leu"},
   {currency_code:"RSD",currency_name:"Serbian Dinar"},
   {currency_code:"RUB",currency_name:"Russian Ruble"},
   {currency_code:"RWF",currency_name:"Rwanda Franc"},
   {currency_code:"SAR",currency_name:"Saudi Riyal"},
   {currency_code:"SBD",currency_name:"Solomon Islands Dollar"},
   {currency_code:"SCR",currency_name:"Seychelles Rupee"},
   {currency_code:"SDG",currency_name:"Sudanese Pound"},
   {currency_code:"SEK",currency_name:"Swedish Krona"},
   {currency_code:"SGD",currency_name:"Singapore Dollar"},
   {currency_code:"SHP",currency_name:"Saint Helena Pound"},
   {currency_code:"SLL",currency_name:"Leone"},
   {currency_code:"SOS",currency_name:"Somali Shilling"},
   {currency_code:"SRD",currency_name:"Surinam Dollar"},
   {currency_code:"SSP",currency_name:"South Sudanese Pound"},
   {currency_code:"STN",currency_name:"Dobra"},
   {currency_code:"SVC",currency_name:"El Salvador Colon"},
   {currency_code:"SYP",currency_name:"Syrian Pound"},
   {currency_code:"SZL",currency_name:"Lilangeni"},
   {currency_code:"THB",currency_name:"Baht"},
   {currency_code:"TJS",currency_name:"Somoni"},
   {currency_code:"TMT",currency_name:"Turkmenistan New Manat"},
   {currency_code:"TND",currency_name:"Tunisian Dinar"},
   {currency_code:"TOP",currency_name:"Pa’anga"},
   {currency_code:"TRY",currency_name:"Turkish Lira"},
   {currency_code:"TTD",currency_name:"Trinidad and Tobago Dollar"},
   {currency_code:"TWD",currency_name:"New Taiwan Dollar"},
   {currency_code:"TZS",currency_name:"Tanzanian Shilling"},
   {currency_code:"UAH",currency_name:"Hryvnia"},
   {currency_code:"UGX",currency_name:"Uganda Shilling"},
   {currency_code:"USD",currency_name:"US Dollar"},
   {currency_code:"USN",currency_name:"US Dollar (Next day)"},
   {currency_code:"UYI",currency_name:"Uruguay Peso en Unidades Indexadas (UI)"},
   {currency_code:"UYU",currency_name:"Peso Uruguayo"},
   {currency_code:"UYW",currency_name:"Unidad Previsional"},
   {currency_code:"UZS",currency_name:"Uzbekistan Sum"},
   {currency_code:"VES",currency_name:"Bolívar Soberano"},
   {currency_code:"VND",currency_name:"Dong"},
   {currency_code:"VUV",currency_name:"Vatu"},
   {currency_code:"WST",currency_name:"Tala"},
   {currency_code:"XAF",currency_name:"CFA Franc BEAC"},
   {currency_code:"XAG",currency_name:"Silver"},
   {currency_code:"XAU",currency_name:"Gold"},
   {currency_code:"XBA",currency_name:"Bond Markets Unit European Composite Unit (EURCO)"},
   {currency_code:"XBB",currency_name:"Bond Markets Unit European Monetary Unit (E.M.U.-6)"},
   {currency_code:"XBC",currency_name:"Bond Markets Unit European Unit of Account 9 (E.U.A.-9)"},
   {currency_code:"XBD",currency_name:"Bond Markets Unit European Unit of Account 17 (E.U.A.-17)"},
   {currency_code:"XCD",currency_name:"East Caribbean Dollar"},
   {currency_code:"XDR",currency_name:"SDR (Special Drawing Right)"},
   {currency_code:"XOF",currency_name:"CFA Franc BCEAO"},
   {currency_code:"XPD",currency_name:"Palladium"},
   {currency_code:"XPF",currency_name:"CFP Franc"},
   {currency_code:"XPT",currency_name:"Platinum"},
   {currency_code:"XSU",currency_name:"Sucre"},
   {currency_code:"XTS",currency_name:"Codes specifically reserved for testing purposes"},
   {currency_code:"XUA",currency_name:"ADB Unit of Account"},
   {currency_code:"XXX",currency_name:"The codes assigned for transactions where no currency is involved"},
   {currency_code:"YER",currency_name:"Yemeni Rial"},
   {currency_code:"ZAR",currency_name:"Rand"},
   {currency_code:"ZMW",currency_name:"Zambian Kwacha"},
   {currency_code:"ZWL",currency_name:"Zimbabwe Dollar"}
],
"LanguageData":[
   {language_name:"Abkhaz",language_code:"ab"},
   {language_name:"Afar",language_code:"aa"},
   {language_name:"Afrikaans",language_code:"af"},
   {language_name:"Akan",language_code:"ak"},
   {language_name:"Albanian",language_code:"sq"},
   {language_name:"Amharic",language_code:"am"},
   {language_name:"Arabic",language_code:"ar"},
   {language_name:"Aragonese",language_code:"an"},
   {language_name:"Armenian",language_code:"hy"},
   {language_name:"Assamese",language_code:"as"},
   {language_name:"Avaric",language_code:"av"},
   {language_name:"Avestan",language_code:"ae"},
   {language_name:"Aymara",language_code:"ay"},
   {language_name:"Azerbaijani",language_code:"az"},
   {language_name:"Bambara",language_code:"bm"},
   {language_name:"Bashkir",language_code:"ba"},
   {language_name:"Basque",language_code:"eu"},
   {language_name:"Belarusian",language_code:"be"},
   {language_name:"Bengali",language_code:"bn"},{language_name:"Bihari",language_code:"bh"},
   {language_name:"Bislama",language_code:"bi"},
   {language_name:"Bosnian",language_code:"bs"},
   {language_name:"Breton",language_code:"br"},
   {language_name:"Bulgarian",language_code:"bg"},
   {language_name:"Burmese",language_code:"my"},
   {language_name:"Catalan",language_code:"ca"},
   {language_name:"Chamorro",language_code:"ch"},
   {language_name:"Chechen",language_code:"ce"},
   {language_name:"Chichewa",language_code:"ny"},
   {language_name:"Chinese",language_code:"zh"},
   {language_name:"Chuvash",language_code:"cv"},
   {language_name:"Cornish",language_code:"kw"},
   {language_name:"Corsican",language_code:"co"},
   {language_name:"Cree",language_code:"cr"},
   {language_name:"Croatian",language_code:"hr"},
   {language_name:"Czech",language_code:"cs"},
   {language_name:"Danish",language_code:"da"},
   {language_name:"Divehi",language_code:"dv"},
   {language_name:"Dutch",language_code:"nl"},
   {language_name:"Dzongkha",language_code:"dz"},
   {language_name:"English",language_code:"en"},
   {language_name:"Esperanto",language_code:"eo"},
   {language_name:"Estonian",language_code:"et"},
   {language_name:"Ewe",language_code:"ee"},
   {language_name:"Faroese",language_code:"fo"},
   {language_name:"Fijian",language_code:"fj"},
   {language_name:"Finnish",language_code:"fi"},
   {language_name:"French",language_code:"fr"},
   {language_name:"Fula",language_code:"ff"},
   {language_name:"Galician",language_code:"gl"},
   {language_name:"Georgian",language_code:"ka"},
   {language_name:"German",language_code:"de"},
   {language_name:"Greek",language_code:"el"},
   {language_name:"Guaraní",language_code:"gn"},
   {language_name:"Gujarati",language_code:"gu"},
   {language_name:"Haitian",language_code:"ht"},
   {language_name:"Hausa",language_code:"ha"},
   {language_name:"Hebrew",language_code:"he"},
   {language_name:"Herero",language_code:"hz"},
   {language_name:"Hindi",language_code:"hi"},
   {language_name:"Hiri Motu",language_code:"ho"},
   {language_name:"Hungarian",language_code:"hu"},
   {language_name:"Interlingua",language_code:"ia"},
   {language_name:"Indonesian",language_code:"id"},
   {language_name:"Interlingue",language_code:"ie"},
   {language_name:"Irish",language_code:"ga"},
   {language_name:"Igbo",language_code:"ig"},
   {language_name:"Inupiaq",language_code:"ik"},
   {language_name:"Ido",language_code:"io"},
   {language_name:"Icelandic",language_code:"is"},
   {language_name:"Italian",language_code:"it"},
   {language_name:"Inuktitut",language_code:"iu"},
   {language_name:"Japanese",language_code:"ja"},
   {language_name:"Javanese",language_code:"jv"},
   {language_name:"Kalaallisut",language_code:"kl"},
   {language_name:"Kannada",language_code:"kn"},
   {language_name:"Kanuri",language_code:"kr"},
   {language_name:"Kashmiri",language_code:"ks"},
   {language_name:"Kazakh",language_code:"kk"},
   {language_name:"Khmer",language_code:"km"},
   {language_name:"Kikuyu",language_code:"ki"},
   {language_name:"Kinyarwanda",language_code:"rw"},
   {language_name:"Kyrgyz",language_code:"ky"},
   {language_name:"Komi",language_code:"kv"},
   {language_name:"Kongo",language_code:"kg"},
   {language_name:"Korean",language_code:"ko"},
   {language_name:"Kurdish",language_code:"ku"},
   {language_name:"Kwanyama",language_code:"kj"},
   {language_name:"Latin",language_code:"la"},
   {language_name:"Luxembourgish",language_code:"lb"},
   {language_name:"Ganda",language_code:"lg"},
   {language_name:"Limburgish",language_code:"li"},
   {language_name:"Lingala",language_code:"ln"},
   {language_name:"Lao",language_code:"lo"},
   {language_name:"Lithuanian",language_code:"lt"},
   {language_name:"Luba-Katanga",language_code:"lu"},
   {language_name:"Latvian",language_code:"lv"},
   {language_name:"Manx",language_code:"gv"},
   {language_name:"Macedonian",language_code:"mk"},
   {language_name:"Malagasy",language_code:"mg"},
   {language_name:"Malay",language_code:"ms"},
   {language_name:"Malayalam",language_code:"ml"},
   {language_name:"Maltese",language_code:"mt"},
   {language_name:"Māori",language_code:"mi"},
   {language_name:"Marathi",language_code:"mr"},
   {language_name:"Marshallese",language_code:"mh"},
   {language_name:"Mongolian",language_code:"mn"},
   {language_name:"Nauru",language_code:"na"},
   {language_name:"Navajo",language_code:"nv"},
   {language_name:"Northern Ndebele",language_code:"nd"},
   {language_name:"Nepali",language_code:"ne"},
   {language_name:"Ndonga",language_code:"ng"},
   {language_name:"Norwegian Bokmål",language_code:"nb"},
   {language_name:"Norwegian Nynorsk",language_code:"nn"},
   {language_name:"Norwegian",language_code:"no"},
   {language_name:"Nuosu",language_code:"ii"},
   {language_name:"Southern Ndebele",language_code:"nr"},
   {language_name:"Occitan",language_code:"oc"},
   {language_name:"Ojibwe",language_code:"oj"},
   {language_name:"Old Church Slavonic",language_code:"cu"},
   {language_name:"Oromo",language_code:"om"},
   {language_name:"Oriya",language_code:"or"},
   {language_name:"Ossetian",language_code:"os"},
   {language_name:"Panjabi",language_code:"pa"},
   {language_name:"Pāli",language_code:"pi"},
   {language_name:"Persian",language_code:"fa"},
   {language_name:"Polish",language_code:"pl"},
   {language_name:"Pashto",language_code:"ps"},
   {language_name:"Portuguese",language_code:"pt"},
   {language_name:"Quechua",language_code:"qu"},
   {language_name:"Romansh",language_code:"rm"},
   {language_name:"Kirundi",language_code:"rn"},
   {language_name:"Romanian",language_code:"ro"},
   {language_name:"Russian",language_code:"ru"},
   {language_name:"Sanskrit",language_code:"sa"},
   {language_name:"Sardinian",language_code:"sc"},
   {language_name:"Sindhi",language_code:"sd"},
   {language_name:"Northern Sami",language_code:"se"},
   {language_name:"Samoan",language_code:"sm"},
   {language_name:"Sango",language_code:"sg"},
   {language_name:"Serbian",language_code:"sr"},
   {language_name:"Gaelic",language_code:"gd"},
   {language_name:"Shona",language_code:"sn"},
   {language_name:"Sinhala",language_code:"si"},
   {language_name:"Slovak",language_code:"sk"},
   {language_name:"Slovene",language_code:"sl"},
   {language_name:"Somali",language_code:"so"},
   {language_name:"Southern Sotho",language_code:"st"},
   {language_name:"Spanish",language_code:"es"},
   {language_name:"Sundanese",language_code:"su"},
   {language_name:"Swahili",language_code:"sw"},
   {language_name:"Swati",language_code:"ss"},
   {language_name:"Swedish",language_code:"sv"},
   {language_name:"Tamil",language_code:"ta"},
   {language_name:"Telugu",language_code:"te"},
   {language_name:"Tajik",language_code:"tg"},
   {language_name:"Thai",language_code:"th"},
   {language_name:"Tigrinya",language_code:"ti"},
   {language_name:"Tibetan Standard",language_code:"bo"},
   {language_name:"Turkmen",language_code:"tk"},
   {language_name:"Tagalog",language_code:"tl"},
   {language_name:"Tswana",language_code:"tn"},
   {language_name:"Tonga",language_code:"to"},
   {language_name:"Turkish",language_code:"tr"},{language_name:"Tsonga",language_code:"ts"},
   {language_name:"Tatar",language_code:"tt"},{language_name:"Twi",language_code:"tw"},
   {language_name:"Tahitian",language_code:"ty"},{language_name:"Uyghur",language_code:"ug"},
   {language_name:"Ukrainian",language_code:"uk"},{language_name:"Urdu",language_code:"ur"},
   {language_name:"Uzbek",language_code:"uz"},{language_name:"Venda",language_code:"ve"},
   {language_name:"Vietnamese",language_code:"vi"},{language_name:"Volapük",language_code:"vo"},
   {language_name:"Walloon",language_code:"wa"},{language_name:"Welsh",language_code:"cy"},
   {language_name:"Wolof",language_code:"wo"},{language_name:"Western Frisian",language_code:"fy"},
   {language_name:"Xhosa",language_code:"xh"},
   {language_name:"Yiddish",language_code:"yi"},{language_name:"Yoruba",language_code:"yo"},
   {language_name:"Zhuang",language_code:"za"},{language_name:"Zulu",language_code:"zu"}
],
"DeviceData":
[
   {user_device:'tablet'},
    {user_device:'mobile'},
    {user_device:'laptop'} 
   ],
   "DaysData":
   [
      {day:'sun'},
      {day:'mon'},
      {day:'tue'},
      {day:'weds'},
      {day:'thur'},
      {day:'fri'},
      {day:'sat'}
       
      ],
};